#! /bin/bash
# prerm script for woodstock
# stolen from libsafe
#
# see: dh_installdeb(1)

[ -n "$SNOOPYDEBUG" ] && set -x

set -e
PRELOAD="/etc/ld.so.preload"
LIBRARY="/lib/woodstock.so"

# summary of how this script can be called:
#        * <prerm> remove'
#        * <old-prerm> upgrade' <new-version>
#        * <new-prerm> failed-upgrade' <old-version>
#        * <conflictor's-prerm> remove' in-favour' <package> <new-version>
#        * <deconfigured's-prerm> deconfigure' in-favour'
#          <package-being-installed> <version> removing'
#          <conflicting-package> <version>
# for details, see /usr/share/doc/packaging-manual/

case "$1" in
    remove|upgrade|deconfigure)
        if [ -e /usr/sbin/ld.so.preload-manager ]; then
            /usr/sbin/ld.so.preload-manager -r $LIBRARY || true
        elif [ -f $PRELOAD ] && grep $LIBRARY $PRELOAD; then
            echo >&2 "Warning:";
            echo >&2 "You have added $LIBRARY to your $PRELOAD file."
            echo >&2 "Continuing with the removal of $LIBRARY without removing the"
            echo >&2 "rerecence to $LIBRARY in $PRELOAD will render your system"
            echo >&2 "unusable by programs that require dynamic linking."
            echo >&2 ""
            echo >&2 "Please continue with the removal after $PRELOAD"
            echo >&2 "has been modified accordingly."
            echo >&2 ""
            echo >&2 "Terminating with error."
            exit 1
        fi
        ;;
    failed-upgrade)
        ;;
    *)
        echo >&2 "prerm called with unknown argument $1"
        exit 1
    ;;
esac

#DEBHELPER#
